// @ts-nocheck
import * as __fd_glob_53 from "../content/docs/sdks/python/parser.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/sdks/python/middleware-flask.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/sdks/python/middleware-fastapi.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/sdks/python/middleware-django.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/sdks/python/installation.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/sdks/python/enforcer.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/sdks/python/discovery.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/sdks/node/parser.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/sdks/node/middleware-vercel.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/sdks/node/middleware-nextjs.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/sdks/node/middleware-express.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/sdks/node/installation.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/sdks/node/enforcer.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/sdks/node/discovery.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/specification/schema-reference.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/specification/overview.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/specification/http-extensions.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/specification/discovery.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/specification/changelog.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/specification/agent-identification.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/sdks/overview.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/introduction/why-apop.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/introduction/what-is-apop.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/introduction/quick-start.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/introduction/ecosystem.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/guides/wordpress.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/guides/policy-templates.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/guides/nextjs.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/guides/fastapi.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/guides/deploy-vercel.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/guides/deploy-docker.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/guides/deploy-cloudflare.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/examples/wordpress.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/examples/saas-api.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/examples/restrictive.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/examples/personal-blog.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/examples/open-data.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/examples/news-publisher.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/examples/multi-protocol.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/examples/healthcare.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/examples/ecommerce.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/contributing/spec-changes.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/contributing/sdk-development.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/contributing/how-to-contribute.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/contributing/conformance-tests.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/sdks/python/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/sdks/node/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/specification/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/sdks/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/guides/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/examples/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/contributing/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "contributing/meta.json": __fd_glob_1, "examples/meta.json": __fd_glob_2, "guides/meta.json": __fd_glob_3, "sdks/meta.json": __fd_glob_4, "specification/meta.json": __fd_glob_5, "sdks/node/meta.json": __fd_glob_6, "sdks/python/meta.json": __fd_glob_7, }, {"index.mdx": __fd_glob_8, "contributing/conformance-tests.mdx": __fd_glob_9, "contributing/how-to-contribute.mdx": __fd_glob_10, "contributing/sdk-development.mdx": __fd_glob_11, "contributing/spec-changes.mdx": __fd_glob_12, "examples/ecommerce.mdx": __fd_glob_13, "examples/healthcare.mdx": __fd_glob_14, "examples/multi-protocol.mdx": __fd_glob_15, "examples/news-publisher.mdx": __fd_glob_16, "examples/open-data.mdx": __fd_glob_17, "examples/personal-blog.mdx": __fd_glob_18, "examples/restrictive.mdx": __fd_glob_19, "examples/saas-api.mdx": __fd_glob_20, "examples/wordpress.mdx": __fd_glob_21, "guides/deploy-cloudflare.mdx": __fd_glob_22, "guides/deploy-docker.mdx": __fd_glob_23, "guides/deploy-vercel.mdx": __fd_glob_24, "guides/fastapi.mdx": __fd_glob_25, "guides/nextjs.mdx": __fd_glob_26, "guides/policy-templates.mdx": __fd_glob_27, "guides/wordpress.mdx": __fd_glob_28, "introduction/ecosystem.mdx": __fd_glob_29, "introduction/quick-start.mdx": __fd_glob_30, "introduction/what-is-apop.mdx": __fd_glob_31, "introduction/why-apop.mdx": __fd_glob_32, "sdks/overview.mdx": __fd_glob_33, "specification/agent-identification.mdx": __fd_glob_34, "specification/changelog.mdx": __fd_glob_35, "specification/discovery.mdx": __fd_glob_36, "specification/http-extensions.mdx": __fd_glob_37, "specification/overview.mdx": __fd_glob_38, "specification/schema-reference.mdx": __fd_glob_39, "sdks/node/discovery.mdx": __fd_glob_40, "sdks/node/enforcer.mdx": __fd_glob_41, "sdks/node/installation.mdx": __fd_glob_42, "sdks/node/middleware-express.mdx": __fd_glob_43, "sdks/node/middleware-nextjs.mdx": __fd_glob_44, "sdks/node/middleware-vercel.mdx": __fd_glob_45, "sdks/node/parser.mdx": __fd_glob_46, "sdks/python/discovery.mdx": __fd_glob_47, "sdks/python/enforcer.mdx": __fd_glob_48, "sdks/python/installation.mdx": __fd_glob_49, "sdks/python/middleware-django.mdx": __fd_glob_50, "sdks/python/middleware-fastapi.mdx": __fd_glob_51, "sdks/python/middleware-flask.mdx": __fd_glob_52, "sdks/python/parser.mdx": __fd_glob_53, });